/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthenticatedUserResponse } from '../../models/authenticated-user-response';

export interface GetAuthenticatedUser$Params {
}

export function getAuthenticatedUser(http: HttpClient, rootUrl: string, params?: GetAuthenticatedUser$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticatedUserResponse>> {
  const rb = new RequestBuilder(rootUrl, getAuthenticatedUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthenticatedUserResponse>;
    })
  );
}

getAuthenticatedUser.PATH = '/api/v1/auth/authenticated-user';
