/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseDto } from '../../models/course-dto';

export interface GetAllCourses$Params {
  id?: string;
  classifierId?: string;
  name?: string;

/**
 * Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
  sort?: Array<string>;
}

export function getAllCourses(http: HttpClient, rootUrl: string, params?: GetAllCourses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CourseDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllCourses.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
    rb.query('classifierId', params.classifierId, {});
    rb.query('name', params.name, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CourseDto>>;
    })
  );
}

getAllCourses.PATH = '/api/v1/courses';
