/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassifierDto } from '../../models/classifier-dto';

export interface FindChildren$Params {
  id: string;
}

export function findChildren(http: HttpClient, rootUrl: string, params: FindChildren$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClassifierDto>>> {
  const rb = new RequestBuilder(rootUrl, findChildren.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClassifierDto>>;
    })
  );
}

findChildren.PATH = '/api/v1/classifiers/{id}/children';
