/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassifierHierarchy } from '../../models/classifier-hierarchy';

export interface GetHierarchyByParentId$Params {
  parentId?: string;
}

export function getHierarchyByParentId(http: HttpClient, rootUrl: string, params?: GetHierarchyByParentId$Params, context?: HttpContext): Observable<StrictHttpResponse<ClassifierHierarchy>> {
  const rb = new RequestBuilder(rootUrl, getHierarchyByParentId.PATH, 'get');
  if (params) {
    rb.query('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClassifierHierarchy>;
    })
  );
}

getHierarchyByParentId.PATH = '/api/v1/classifiers';
