/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClassifierNode } from '../models/classifier-node';
export interface ClassifierHierarchy {
  nodes?: Array<ClassifierNode>;
}
