/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClassifierNode {
  children?: Array<ClassifierNode>;
  id?: string;
  leaf?: boolean;
  lvl?: number;
  name?: string;
  parentId?: string;
  seqOrder?: number;
}
