/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseModuleDto {
  description?: string;
  id?: string;
  name: string;
  seqOrder: number;
  title: string;
}
