/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseDto {
  acquiredSkills?: Array<string>;
  classifierId: string;
  cost?: number;
  description?: string;
  format?: string;
  id?: string;
  image?: string;
  name: string;
  targetAudience?: Array<string>;
  totalDuration?: string;
  totalHours?: number;
}
