/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StaffDto } from '../models/staff-dto';
export interface CourseStaffDto {
  active: boolean;
  admin: boolean;
  author: boolean;
  id?: string;
  instructor: boolean;
  methodist: boolean;
  moderator: boolean;
  showInPromo: boolean;
  staff: StaffDto;
}
