/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInfo {
  birthdate?: string;
  email?: string;
  emailVerified?: boolean;
  familyName?: string;
  givenName?: string;
  id?: string;
  name?: string;
  nickname?: string;
  preferredUsername?: string;
  roles?: Array<string>;
  updatedAt?: string;
  username?: string;
}
