/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the EDUApiConfiguration configuration object with a given root URL.
 */
export function provideEDUApiConfiguration(rootUrl: string) {
  var config = new EDUApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: EDUApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class EDUApiConfiguration {
  rootUrl: string = 'http://acadeland.ru:8080';
}

/**
 * Parameters for `EDUApiModule.forRoot()`
 */
export interface EDUApiConfigurationParams {
  rootUrl?: string;
}
