/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseModuleDto } from '../../models/course-module-dto';

export interface FindAllByCourseId1$Params {
  courseId: string;
}

export function findAllByCourseId1(http: HttpClient, rootUrl: string, params: FindAllByCourseId1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CourseModuleDto>>> {
  const rb = new RequestBuilder(rootUrl, findAllByCourseId1.PATH, 'get');
  if (params) {
    rb.query('courseId', params.courseId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CourseModuleDto>>;
    })
  );
}

findAllByCourseId1.PATH = '/api/v1/course-modules';
