/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseStaffDto } from '../../models/course-staff-dto';

export interface FindAllByCourseId$Params {
  courseId: string;
}

export function findAllByCourseId(http: HttpClient, rootUrl: string, params: FindAllByCourseId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CourseStaffDto>>> {
  const rb = new RequestBuilder(rootUrl, findAllByCourseId.PATH, 'get');
  if (params) {
    rb.query('courseId', params.courseId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CourseStaffDto>>;
    })
  );
}

findAllByCourseId.PATH = '/api/v1/course-staffs';
